### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by Seon82** [tympanix/subsync#10]
Hello,
First of all, thanks for taking the time of sharing this project!
I'm getting this error when I run:
>python -m subsync moviename.mp4 

....................................................................................................
Windows 10, Python 3.6.3
....................................................................................................
Traceback (most recent call last):
  File "C:\Program Files (x86)\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals) 
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\subsync\__main__.py", line 4, in <module>
    run() 
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\subsync\main.py", line 42, in run
    m.mfcc(duration=args.duration, seek=not args.start)  
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\subsync\media.py", line 83, in mfcc
    transcode = Transcode(self.filepath, duration=duration, seek=seek)
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\subsync\ffmpeg.py", line 28, in __init__
    self.length = self.__length()
  File "C:\Program Files (x86)\Miniconda3\lib\site-packages\subsync\ffmpeg.py", line 55, in __length
    cmd = subprocess.Popen(['ffprobe', self.input], stdout=PIPE, stderr=STDOUT)
  File "C:\Program Files (x86)\Miniconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Miniconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
....................................................................................................

I don't really know what's happening here... reinstalling didn't help, and I get the error both when the subtitle is within a mkv container and when it's a separate file.

**Comment by tympanix** [comment]
This is definitely an error. I believe if you `cd ..` and then try the command from there it should recognize the file path. I will make sure to fix this mistake.

**Comment by Seon82** [comment]
Unfortunately, that does not seem to fix the issue for me, and the error message hasn't changed either.
(I've tried both  `python -m subsync  directoryname\moviename.mp4` and `python -m subsync moviename.mp4` after moving up a directory)

**Comment by tympanix** [comment]
Odd indeed. I will try to investigate. If you can help, it would be interesting to see which path it uses when producing the `FileNotFound` exception with a print statement. Also maybe try to rename the files as to not include special characters.

**Comment by Seon82** [comment]
Indeed, I hadn't installed ffmpeg and that was causing the issue - all works fine now.
Thank you very much for your quick help, and thumbs up for this great project!
