### ISSUE TITLE
most working but some give errors

### ISSUE THREAD

**Issue by huuub** [tympanix/subsync#12]
any help?

Traceback (most recent call last):
  File "/home/jeroen/.local/bin/subsync", line 4, in <module>
    subsync.run()
  File "/home/jeroen/.local/lib/python3.6/site-packages/subsync/main.py", line 42, in run
    m.mfcc(duration=args.duration, seek=not args.start)
  File "/home/jeroen/.local/lib/python3.6/site-packages/subsync/media.py", line 83, in mfcc
    transcode = Transcode(self.filepath, duration=duration, seek=seek)
  File "/home/jeroen/.local/lib/python3.6/site-packages/subsync/ffmpeg.py", line 28, in __init__
    self.length = self.__length()
  File "/home/jeroen/.local/lib/python3.6/site-packages/subsync/ffmpeg.py", line 57, in __length
    match = re.search(r'(\d\d):(\d\d):(\d\d)\.(\d\d)', duration[0])
IndexError: list index out of range

**Comment by tympanix** [comment]
We are invoking `ffprobe` to find the length of the video file here: https://github.com/tympanix/subsync/blob/661bc6856c6e428ec115bac85e053050d17a7fc1/subsync/ffmpeg.py#L55-L60

Apparently the output of the `ffprobe` command is something unexpected and therefore it does not match the regex. If you may, try to run the command on the same file in a terminal and paste it here. Then we might know why it does not match the expected output.

**Comment by tympanix** [comment]
Maybe we can make the `ffprobe` invokation more robust with some tricks mentioned in the [documentation](http://trac.ffmpeg.org/wiki/FFprobeTips#Formatcontainerduration)

**Comment by huuub** [comment]
The output is empty for that one. For a normal one it is something like 
['  Duration: 01:42:33.38, start: 0.000000, bitrate: 11643 kb/s\n']

**Comment by tympanix** [comment]
Ok, that is a problem. Do you get a non-zero exit code? Maybe the video file is unsupported by ffmpeg or it is corrupt in some way 🤔

**Comment by huuub** [comment]
I don't think so, the code goes further. 
However I have 2 types of error which I get a lot more. I will make 2 other issues for them.

**Comment by huuub** [comment]
Contact me at huuubAThuuubDOTcom and I give you an FTP user where you can download the problem videos? That is maybe easier...

**Comment by huuub** [comment]
I think you can close/remove this one.
I really want to thank you for this one. Great tool!!!
The out of sync subtitles were a real pain.
